// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"exact":true,"path":"/","redirect":"/docs","parentId":"@@/global-layout","id":"1"},"2":{"exact":true,"path":"/docs","parentId":"@@/global-layout","id":"2"},"3":{"exact":true,"path":"/posts/:postId","parentId":"@@/global-layout","id":"3"},"4":{"exact":true,"path":"","parentId":"5","id":"4","originPath":"/user"},"5":{"path":"/user","isWrapper":true,"parentId":"@@/global-layout","id":"5"},"6":{"exact":true,"path":"/login","parentId":"@@/global-layout","id":"6"},"7":{"path":"*","parentId":"@@/global-layout","id":"7"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__docs" */'@/pages/docs.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__posts__postId" */'@/pages/posts/[postId].tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__user" */'@/pages/user.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "wrappers__auth" */'@/wrappers/auth.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__login" */'@/pages/login.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Volumes/F/zyl-study/web-zhuawa/umi-app/src/layouts/index.tsx')),
},
  };
}
